Code.require_file("../tests.exs", __DIR__)

# Additional test cases supported by selenium
Code.require_file("../cases/browser/double_click_test.exs", __DIR__)
Code.require_file("../cases/browser/frames_test.exs", __DIR__)
Code.require_file("../cases/browser/hover_test.exs", __DIR__)
Code.require_file("../cases/element/hover_test.exs", __DIR__)
Code.require_file("../cases/browser/move_mouse_by_test.exs", __DIR__)
Code.require_file("../cases/browser/window_handles_test.exs", __DIR__)
Code.require_file("../cases/browser/window_position_test.exs", __DIR__)
Code.require_file("../cases/element/size_test.exs", __DIR__)
Code.require_file("../cases/element/location_test.exs", __DIR__)
Code.require_file("../cases/feature/use_feature_test.exs", __DIR__)
Code.require_file("../cases/feature/import_feature_test.exs", __DIR__)
Code.require_file("../cases/feature/automatic_screenshot_test.exs", __DIR__)
