name: Lint Commit
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - edited
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited

jobs:
  commitlint:
    runs-on: ubuntu-latest
    name: commitlint

    steps:
      - uses: actions/checkout@v4
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          subjectPattern: ^(?![A-Z]).+$
